# Generated by Django 4.1 on 2022-09-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudpilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='accessLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='button',
            name='color',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button',
            name='command',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button',
            name='isOn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='button',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
