# Generated by Django 4.1 on 2022-09-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudpilot', '0002_button_accesslevel_button_color_button_command_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='color',
        ),
    ]
